In [1]:
import numpy as np
import urllib
import cv2

In [4]:
def detect_faces_on_frames(frame):
    height, width, depth = frame.shape

    # create grayscale version
    grayscale = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
 
    # equalize histogram
    cv2.equalizeHist(grayscale, grayscale)

    # detect objects
    classifier = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
    DOWNSCALE = 4
    minisize = (frame.shape[1]/DOWNSCALE,frame.shape[0]/DOWNSCALE)
    miniframe = cv2.resize(frame, minisize)
    faces = classifier.detectMultiScale(miniframe)
    
    return faces

In [2]:
def detect_faces_on_image(img):
    # Create the haar cascade
    face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
    # Read the image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    
    print "foram detectadas {0} faces, probabilidade de felinos 20%, probabilidade de caninos, 0% {0}".format(len(faces))

    # Draw a rectangle around the faces
    for i, (x, y, w, h) in enumerate(faces):
        
        print str(i)+" Face: ("+ str(x) + "," + str(y) + ")"
        img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    
    return img
    


In [6]:
#Carregando imagem de arquivo local
def detect_faces_on_local_images():
    img = cv2.imread('family.png')
    img = detect_faces_on_image(img)
    cv2.imshow('image',img)
    #quit if press ESC
    if cv2.waitKey() & 0xff == 27:
        quit()

In [7]:
def detect_faces_on_url_images():
    req = urllib.urlopen('http://tutores.com.br/blog/wp-content/uploads/familia.png')
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv2.imdecode(arr,-1) # 'load it as it is'
    img = detect_faces_on_image(img)
    cv2.imshow('image',img)
    if cv2.waitKey() & 0xff == 27: 
        quit()

In [8]:
def detect_faces_on_webcam():
    cap = cv2.VideoCapture(0)
    while(True):
        # Capture frame-by-frame
        ret, frame = cap.read()
        
        faces = detect_faces_on_frames(frame)
        
        #Printing faces detected
        DOWNSCALE = 4
        if len(faces)>0:
            for i in faces:
                x, y, w, h = [ v*DOWNSCALE for v in i ]
                cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0))

        # Display the resulting frame
        cv2.imshow('frame',frame)
        
        #Break if press ESC
        if cv2.waitKey(1) & 0xFF == 27:
            break

    # When everything done, release the capture
    cap.release()
    print "foram detectadas {0} faces, probabilidade de felinos 20%, probabilidade de caninos, 0% {0}".format(len(faces))
    if cv2.waitKey() & 0xFF == 27:
        quit()
    
    

In [7]:
detect_faces_on_local_images()()

foram detectadas 3 faces, probabilidade de felinos 20%, probabilidade de caninos, 0% 3
0 Face: (240,107)
1 Face: (331,105)
2 Face: (431,82)


TypeError: 'NoneType' object is not callable

In [7]:
detect_faces_on_url_images()

foram detectadas 3 faces, probabilidade de felinos 20%, probabilidade de caninos, 0% 3
0 Face: (820,160)
1 Face: (618,193)
2 Face: (464,214)


In [9]:
detect_faces_on_webcam()

[122  43  79  79] Face: (488,172)
[124  42  77  77] Face: (496,168)
[125  43  76  76] Face: (500,172)
[121  42  79  79] Face: (484,168)
[118  41  80  80] Face: (472,164)
[117  44  74  74] Face: (468,176)
[115  46  73  73] Face: (460,184)
[113  47  70  70] Face: (452,188)
[112  46  72  72] Face: (448,184)
[111  44  74  74] Face: (444,176)
[117  46  70  70] Face: (468,184)
[115  44  73  73] Face: (460,176)
[116  45  72  72] Face: (464,180)
[118  47  69  69] Face: (472,188)
[117  46  71  71] Face: (468,184)
[116  45  73  73] Face: (464,180)
[116  44  74  74] Face: (464,176)
[113  45  74  74] Face: (452,180)
[108  43  80  80] Face: (432,172)
[109  44  78  78] Face: (436,176)
[111  44  76  76] Face: (444,176)
[109  44  78  78] Face: (436,176)
[111  45  74  74] Face: (444,180)
[111  44  76  76] Face: (444,176)
[112  44  75  75] Face: (448,176)
[112  45  74  74] Face: (448,180)
[113  45  72  72] Face: (452,180)
foram detectadas 1 faces, probabilidade de felinos 20%, probabilidade de caninos, 